[package]
description = "Parity Secret Store"
name = "parity-secretstore"
version = "1.0.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
byteorder = "1.0"
ethabi = "12.0"
ethabi-contract = "11.0"
ethabi-derive = "12.0"
ethereum-types = "0.9.0"
futures = "0.1"
hyper = { version = "0.12", default-features = false }
keccak-hash = "0.5.1"
kvdb = "0.6.0"
kvdb-rocksdb = "0.8.0"
lazy_static = "1.0"
libsecp256k1 = { version = "0.3.5", default-features = false }
log = "0.4"
parity-bytes = "0.1"
parity-crypto = { version = "0.6.0", features = ["publickey"] }
parity-runtime = "0.1.1"
parking_lot = "0.10.0"
percent-encoding = "2.1.0"
rustc-hex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiny-keccak = "1.4"
tokio = "0.1.22"
tokio-io = "0.1"
tokio-service = "0.1"
url = "2.1.0"
jsonrpc-server-utils = "14.0.3"
rlp = "0.4"
jsonrpc-core-client = { version = "14.2.0", features = ["http"] }

[dev-dependencies]
env_logger = "0.5"
tempdir = "0.3"
parity-runtime = { version = "0.1.1", features = ["test-helpers"] }
jsonrpc-http-server = "14.2"

[features]
ci = [] # disables some tests that don't run in CI
