# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Local Development Chain
chain = "dev-chainspec.json"
# No updates will be auto-installed
auto_update = "none"
base_path = "chain2"
mode = "active"

[rpc]
disable = true

[ui]
disable = true

[ipc]
disable = true

[websockets]
disable = true

[snapshots]
disable_periodic = true

[misc]
# Logs will be stored at openethereum.log.
log_file = "chain2.log"

[network]
port = 30303
bootnodes = [
    #"enode_address@node_address:30303"
    "enode://f3480ddd319ebf0817f911f028023dd5c9d1aa0b3d1363f80bc1adc233c1e0d2e8afdf200272f2b986266ec76fdca580f61d3cbdfcb41e4be8b1d1eee2e4ba36@10.0.0.20:30303",
    "enode://efe6c1d2f8bae0045b32e392a9be3fc4a06ee949ab199c6f47458ec3965d949295c2eef32a0d882c21aaf800a93628b4bc310d47f9cbfc4b31a9873062c03f2d@10.0.0.21:30303"
]

[secretstore]
disable = true

[account]
password = ["config/account.pwd"]
